In [5]:
import numpy as np
import math as m
np.set_printoptions(precision = 3, suppress = True)

In [42]:
def dhTransform(dhTable): 
    
    no_links = dhTable.shape[0]
    listofTransforms = []
    for i in range(no_links):
        T = singleTransform(dhTable[i][0], dhTable[i][1], dhTable[i][2], dhTable[i][3])
        listofTransforms.append(T)
    return multipleTransform(listofTransforms)
    
def singleTransform(theta, d, alphaPrev, offsetPrev): 
    
    T = np.array([[m.cos(theta), -m.sin(theta), 0, offsetPrev], 
                  [m.sin(theta)*m.cos(alphaPrev), m.cos(theta)*m.cos(alphaPrev), -m.sin(alphaPrev), -m.sin(alphaPrev)*d], 
                  [m.sin(theta)*m.sin(alphaPrev), m.cos(theta)*m.sin(alphaPrev), m.cos(alphaPrev), m.cos(alphaPrev)*d],
                    [0, 0, 0, 1]])
    
    return T

def multipleTransform(listofTransforms): 
    if len(listofTransforms)==1: 
        return listofTransforms[0]
    else: 
        prevT = listofTransforms.pop(0)
        return np.matmul(prevT, multipleTransform(listofTransforms))

def vec2SO3(omega, theta): 
    
    if np.linalg.norm(omega) > 1: 
        omega = omega/np.linalg.norm(omega)
        
    omegaSE3 = np.array([[0, -omega[0][2], omega[0][1]], [omega[0][2], 0, -omega[0][0]], [-omega[0][1], omega[0][0], 0]])
    R = np.eye(3) + m.sin(theta)*omegaSE3 + (1-m.cos(theta))*np.matmul(omegaSE3, omegaSE3)
    return R 

In [9]:
theta = np.pi/3
d = 0
alphaPrev = 0
offsetPrev = 1.0

In [32]:
k = singleTransform(np.pi/4, 0, 0, 1)
h = singleTransform(np.pi/4, 0, 0, 0)

In [37]:
k

array([[ 0.707, -0.707,  0.   ,  1.   ],
       [ 0.707,  0.707, -0.   , -0.   ],
       [ 0.   ,  0.   ,  1.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  1.   ]])

In [35]:
h

array([[ 0.707, -0.707,  0.   ,  0.   ],
       [ 0.707,  0.707, -0.   , -0.   ],
       [ 0.   ,  0.   ,  1.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  1.   ]])

In [41]:
dhTable = np.array([[np.pi/4, 0, 0, 0], [-np.pi/4, 0, 0, 1], [-np.pi/4, 0, 0, 1], [np.pi/4, 0, 0, 1]])
dhTransform(dhTable)

array([[ 1.   ,  0.   ,  0.   ,  2.414],
       [ 0.   ,  1.   ,  0.   , -0.   ],
       [ 0.   ,  0.   ,  1.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  1.   ]])

In [54]:
omega = np.array([[0, 0.866, 0.5]])
theta = np.pi/6
omega

array([[0.   , 0.866, 0.5  ]])

In [55]:
R = vec2SO3(omega, theta)
R

array([[ 0.866, -0.25 ,  0.433],
       [ 0.25 ,  0.967,  0.058],
       [-0.433,  0.058,  0.9  ]])